apiVersion: v1
kind: Service
metadata:
  name: service-api
  namespace: nagp-kubeapp
spec:
  selector:
    app: service-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      name: http
