// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceApi.Data;

#nullable disable

namespace ServiceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "userone@example.com",
                            Name = "User One"
                        },
                        new
                        {
                            Id = 2,
                            Email = "usertwo@example.com",
                            Name = "User Two"
                        },
                        new
                        {
                            Id = 3,
                            Email = "userthree@example.com",
                            Name = "User Three"
                        },
                        new
                        {
                            Id = 4,
                            Email = "userfour@example.com",
                            Name = "User Four"
                        },
                        new
                        {
                            Id = 5,
                            Email = "userfive@example.com",
                            Name = "User Five"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
