apiVersion: v1
kind: ConfigMap
metadata:
  name: nagp-service-api-config
data:
  SQL_SERVER: "sqlserver"
  SQL_DB: "SampleDb"
  SQL_USER: "sa"
  # SQL_PASSWORD is now stored in a Kubernetes Secret for security